/**
 * Self-Extension Tools — expose plugin self-extension to the agent (Issue #210).
 *
 * Tools:
 *  - memory_propose_tool:    manually trigger gap analysis and generate tool proposals
 *  - memory_tool_proposals:  list current proposals with status
 *  - memory_tool_approve:    approve a proposal (marks it for implementation)
 *  - memory_tool_reject:     reject a proposal
 */

import { Type } from "@sinclair/typebox";
import type { ClawdbotPluginApi } from "openclaw/plugin-sdk/core";
import type { ToolProposalStore } from "../backends/tool-proposal-store.js";
import type { WorkflowStore } from "../backends/workflow-store.js";
import type { HybridMemoryConfig } from "../config.js";
import { capturePluginError } from "../services/error-reporter.js";
import { GapDetector } from "../services/gap-detector.js";
import { ToolProposer } from "../services/tool-proposer.js";

export interface SelfExtensionToolsContext {
  toolProposalStore: ToolProposalStore;
  workflowStore: WorkflowStore;
  cfg: HybridMemoryConfig;
}

export function registerSelfExtensionTools(ctx: SelfExtensionToolsContext, api: ClawdbotPluginApi): void {
  const { toolProposalStore, workflowStore, cfg } = ctx;

  // -------------------------------------------------------------------------
  // memory_propose_tool — trigger gap analysis and generate proposals
  // -------------------------------------------------------------------------
  api.registerTool({
    name: "memory_propose_tool",
    label: "Propose New Tool from Usage Gaps",
    description:
      "Analyse workflow traces to detect recurring multi-step workarounds and generate tool proposals. Each proposal is a specification (not code) that a human or LLM can implement later. Requires selfExtension.enabled = true.",
    parameters: Type.Object({
      minFrequency: Type.Optional(
        Type.Integer({
          minimum: 1,
          description: "Override: minimum times a gap must be observed (default from config).",
        }),
      ),
      minToolSavings: Type.Optional(
        Type.Integer({
          minimum: 1,
          description: "Override: minimum tool calls saved per invocation (default from config).",
        }),
      ),
    }),
    async execute(_toolCallId: string, params: Record<string, unknown>) {
      const { minFrequency, minToolSavings } = params as {
        minFrequency?: number;
        minToolSavings?: number;
      };

      try {
        const gapDetector = new GapDetector(workflowStore);
        const proposer = new ToolProposer(gapDetector, toolProposalStore, cfg.selfExtension);
        const result = proposer.runCycle({
          ...(minFrequency !== undefined ? { minFrequency } : {}),
          ...(minToolSavings !== undefined ? { minToolSavings } : {}),
        });

        const lines: string[] = [];
        lines.push("Self-extension analysis complete.");
        lines.push(`  Proposed: ${result.proposed}`);
        lines.push(`  Skipped:  ${result.skipped}`);
        if (result.reasons.length > 0) {
          lines.push("  Details:");
          result.reasons.forEach((r) => lines.push(`    - ${r}`));
        }
        if (result.proposed > 0) {
          lines.push("");
          lines.push("Use memory_tool_proposals to review proposals.");
          lines.push("Use memory_tool_approve <id> to mark a proposal as approved.");
        }

        return {
          content: [{ type: "text", text: lines.join("\n") }],
          details: result,
        };
      } catch (err) {
        capturePluginError(err instanceof Error ? err : new Error(String(err)), {
          subsystem: "self-extension",
          operation: "memory-propose-tool",
          phase: "runtime",
        });
        throw err;
      }
    },
  });

  // -------------------------------------------------------------------------
  // memory_tool_proposals — list proposals
  // -------------------------------------------------------------------------
  api.registerTool({
    name: "memory_tool_proposals",
    label: "List Tool Proposals",
    description:
      "List tool proposals generated by the self-extension gap analyser. Filter by status (proposed/approved/rejected/implemented). Each proposal includes the tool name, rationale, and ID needed for approve/reject actions.",
    parameters: Type.Object({
      status: Type.Optional(
        Type.Union(
          [Type.Literal("proposed"), Type.Literal("approved"), Type.Literal("rejected"), Type.Literal("implemented")],
          {
            description: "Filter by proposal status. Omit to list all proposals.",
          },
        ),
      ),
      limit: Type.Optional(
        Type.Integer({
          minimum: 1,
          maximum: 100,
          description: "Maximum number of proposals to return. Default: 20.",
        }),
      ),
    }),
    async execute(_toolCallId: string, params: Record<string, unknown>) {
      const { status, limit } = params as {
        status?: "proposed" | "approved" | "rejected" | "implemented";
        limit?: number;
      };

      try {
        const proposals = toolProposalStore.list({
          status,
          limit: limit ?? 20,
        });

        if (proposals.length === 0) {
          return {
            content: [
              {
                type: "text",
                text: status
                  ? `No ${status} tool proposals found.`
                  : "No tool proposals found. Run memory_propose_tool to generate proposals.",
              },
            ],
            details: [],
          };
        }

        const lines = proposals.map((p, i) => {
          let sourceInfo = "";
          try {
            const sources = JSON.parse(p.sourcePatterns) as string[];
            if (sources.length > 0) {
              sourceInfo = ` | from ${sources.length} pattern(s)`;
            }
          } catch {
            // ignore
          }
          return (
            `${i + 1}. [${p.status.toUpperCase()}] ${p.name}${sourceInfo}\n` +
            `   ID: ${p.id}\n` +
            `   ${p.description}\n` +
            `   Created: ${p.createdAt}`
          );
        });

        const summary = `Found ${proposals.length} proposal(s)${status ? ` (${status})` : ""}:\n\n${lines.join("\n\n")}`;

        return {
          content: [{ type: "text", text: summary }],
          details: proposals,
        };
      } catch (err) {
        capturePluginError(err instanceof Error ? err : new Error(String(err)), {
          subsystem: "self-extension",
          operation: "memory-tool-proposals",
          phase: "runtime",
        });
        throw err;
      }
    },
  });

  // -------------------------------------------------------------------------
  // memory_tool_approve — approve a pending proposal
  // -------------------------------------------------------------------------
  api.registerTool({
    name: "memory_tool_approve",
    label: "Approve Tool Proposal",
    description:
      "Approve a pending tool proposal. Marks it as approved so a human or LLM can implement it. Requires the proposal ID from memory_tool_proposals.",
    parameters: Type.Object({
      id: Type.String({
        description: "The proposal ID to approve (from memory_tool_proposals).",
      }),
    }),
    async execute(_toolCallId: string, params: Record<string, unknown>) {
      const { id } = params as { id: string };

      try {
        const gapDetector = new GapDetector(workflowStore);
        const proposer = new ToolProposer(gapDetector, toolProposalStore, cfg.selfExtension);
        const result = proposer.approveProposal(id);

        return {
          content: [
            {
              type: "text",
              text: result.success ? `✅ ${result.message}` : `❌ ${result.message}`,
            },
          ],
          details: result,
        };
      } catch (err) {
        capturePluginError(err instanceof Error ? err : new Error(String(err)), {
          subsystem: "self-extension",
          operation: "memory-tool-approve",
          phase: "runtime",
        });
        throw err;
      }
    },
  });

  // -------------------------------------------------------------------------
  // memory_tool_reject — reject a pending proposal
  // -------------------------------------------------------------------------
  api.registerTool({
    name: "memory_tool_reject",
    label: "Reject Tool Proposal",
    description:
      "Reject a pending tool proposal. The gap will no longer be surfaced unless re-analysed. Requires the proposal ID from memory_tool_proposals.",
    parameters: Type.Object({
      id: Type.String({
        description: "The proposal ID to reject (from memory_tool_proposals).",
      }),
    }),
    async execute(_toolCallId: string, params: Record<string, unknown>) {
      const { id } = params as { id: string };

      try {
        const gapDetector = new GapDetector(workflowStore);
        const proposer = new ToolProposer(gapDetector, toolProposalStore, cfg.selfExtension);
        const result = proposer.rejectProposal(id);

        return {
          content: [
            {
              type: "text",
              text: result.success ? `✅ ${result.message}` : `❌ ${result.message}`,
            },
          ],
          details: result,
        };
      } catch (err) {
        capturePluginError(err instanceof Error ? err : new Error(String(err)), {
          subsystem: "self-extension",
          operation: "memory-tool-reject",
          phase: "runtime",
        });
        throw err;
      }
    },
  });
}
