import { getEnv } from "../utils/env-manager.js";
/**
 * Skill Crystallizer — generate SKILL.md files from workflow patterns (Issue #208).
 *
 * Takes a crystallization candidate (pattern + metadata) and produces a SKILL.md
 * following the AgentSkill format. Optionally generates a helper shell script
 * when the pattern is composed entirely of exec calls.
 */

import { homedir } from "node:os";
import type { WorkflowPattern } from "../backends/workflow-store.js";
import type { CrystallizationConfig } from "../config/types/features.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

interface CrystallizationInput {
  patternId: string;
  pattern: WorkflowPattern;
}

interface CrystallizationResult {
  skillName: string;
  skillContent: string;
  /** Resolved output path for the SKILL.md (not yet written to disk — requires approval) */
  proposedOutputPath: string;
  /** Whether a companion shell script was generated */
  hasScript: boolean;
  /** Shell script content if hasScript === true */
  scriptContent?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toTitleCase(value: string): string {
  return value
    .split("-")
    .filter((part) => part.length > 0)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(" ");
}

export function normalizeSkillName(value: string): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  return normalized.length > 0 ? normalized : "auto-generated-skill";
}

/**
 * Derive a kebab-case skill name from example goals and tool sequence.
 * Prefers the first example goal, falls back to tool sequence hash.
 */
export function deriveSkillName(exampleGoals: string[], toolSequence: string[], patternId: string): string {
  // Try to extract a short phrase from the first example goal
  const firstGoal = exampleGoals[0];
  if (firstGoal && firstGoal.trim().length > 0) {
    const slug = firstGoal
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, "")
      .trim()
      .split(/\s+/)
      .slice(0, 4)
      .join("-");
    if (slug.length >= 3) return normalizeSkillName(`auto-${slug}`);
  }

  // Fall back: use the first two tool names + hash fragment (lowercase for consistency)
  const toolSlug = toolSequence
    .slice(0, 2)
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-");
  return normalizeSkillName(`auto-${toolSlug}-${patternId.slice(0, 6)}`);
}

/**
 * Check whether a tool sequence is entirely exec calls (shell-automatable).
 */
export function isExecOnlySequence(toolSequence: string[]): boolean {
  return toolSequence.length > 0 && toolSequence.every((t) => t === "exec");
}

// ---------------------------------------------------------------------------
// SKILL.md template builder
// ---------------------------------------------------------------------------

function buildSkillContent(skillName: string, pattern: WorkflowPattern, patternId: string, createdAt: string): string {
  const toolSequence = pattern.toolSequence;
  const successPct = Math.round(pattern.successRate * 100);
  const normalizedGoals = pattern.exampleGoals
    .filter((goal) => goal.trim().length > 0)
    .map((goal) => goal.replace(/\s+/g, " ").trim());
  const exampleGoalsText =
    normalizedGoals.length > 0
      ? normalizedGoals.map((g) => `- ${g}`).join("\n")
      : "- Match a task that follows this workflow.";
  const primaryGoal = normalizedGoals[0] ?? `follow the ${skillName} workflow`;
  const shortGoal = primaryGoal.length > 120 ? `${primaryGoal.slice(0, 117).trimEnd()}...` : primaryGoal;
  const description = `Use when the user asks to ${shortGoal}. Auto-crystallized from repeated workflow evidence.`;
  const workflowText = toolSequence
    .map(
      (tool, i) =>
        `${i + 1}. Use \`${tool}\` for step ${i + 1} of the bounded workflow, then confirm the result before continuing.`,
    )
    .join("\n");
  const nearMiss = `Do not use for requests that only discuss ${shortGoal} without asking you to run the workflow.`;

  return `---
name: ${skillName}
description: ${description}
category: crystallized-workflow
provenance: pattern:${patternId}
---

# ${toTitleCase(skillName)}

> Auto-crystallized from workflow pattern on ${createdAt}.
> **Do not edit this file manually** — it will be regenerated or overwritten.

## Trigger

Use this skill when the request clearly matches the recurring workflow captured by this pattern.

Positive examples:
${exampleGoalsText}

## Scope

This skill is for a bounded, repeatable workflow that follows the recorded tool sequence and validation checks.

## When not to use

- ${nearMiss}
- Do not use for unrelated planning, open-ended explanation requests, or broader tasks that need a different workflow.
- Do not improvise destructive or credential-handling steps that are not present in this generated skill.

## Workflow

${workflowText}

## Verification

- Confirm each step produced the expected artifact or observable before moving on.
- Prefer objective checks (files exist, command exit codes, structured output) over subjective judgment.
- Stop and ask for clarification when validation signals are ambiguous or missing.

## Anti-patterns / Known Failures

- Do not paste raw transcripts, stack traces, or multi-page logs into follow-up work; summarize as checklist updates.
- Do not skip verification because a step "probably" succeeded without evidence.
- Do not broaden scope beyond the captured tool sequence unless the user explicitly expands the task.

## Examples

- Positive: "${shortGoal}"
- Negative: "How do I create a GitHub issue?"
- Edge: "Explain ${shortGoal} without executing the workflow or changing files."

## Provenance

- Source pattern ID: \`${patternId}\`
- Success rate: ${successPct}% (${pattern.successCount}/${pattern.totalCount} executions)
- Average duration: ${pattern.avgDurationMs}ms
- Tool sequence: \`${toolSequence.join(" → ")}\`
- Approval was required before this file was written.
`;
}

// ---------------------------------------------------------------------------
// SkillCrystallizer
// ---------------------------------------------------------------------------

export class SkillCrystallizer {
  constructor(private readonly cfg: CrystallizationConfig) {}

  /**
   * Generate a SKILL.md from a crystallization candidate.
   * Does NOT write to disk — returns content + proposed path for the approval flow.
   */
  crystallize(input: CrystallizationInput): CrystallizationResult {
    const { patternId, pattern } = input;
    const createdAt = new Date().toISOString().slice(0, 10);

    const skillName = deriveSkillName(pattern.exampleGoals, pattern.toolSequence, patternId);
    const skillContent = buildSkillContent(skillName, pattern, patternId, createdAt);

    // Resolve output directory (expand ~ for home dir)
    const outputDir = this.cfg.outputDir.replace(/^~/, getEnv("HOME") || homedir());
    const proposedOutputPath = `${outputDir}/${skillName}/SKILL.md`;

    // Generate shell script for exec-only sequences
    const hasScript = isExecOnlySequence(pattern.toolSequence);
    const scriptContent = hasScript ? buildShellScript(skillName, pattern, patternId) : undefined;

    return {
      skillName,
      skillContent,
      proposedOutputPath,
      hasScript,
      scriptContent,
    };
  }
}

// ---------------------------------------------------------------------------
// Shell script builder (exec-only patterns)
// ---------------------------------------------------------------------------

function buildShellScript(skillName: string, pattern: WorkflowPattern, patternId: string): string {
  const steps = pattern.toolSequence.map((_, i) => `# Step ${i + 1}: exec call`).join("\n");
  return `#!/usr/bin/env bash
# Auto-generated shell script for skill: ${skillName}
# Pattern ID: ${patternId}
# Steps: ${pattern.toolSequence.length} exec call(s)
# Success rate: ${Math.round(pattern.successRate * 100)}%

set -euo pipefail

${steps}

echo "Skill '${skillName}' scaffold generated. Replace each '# Step N' block with concrete commands before use."
`;
}
