import { getEnv } from "../utils/env-manager.js";
/**
 * Skill Crystallizer — generate SKILL.md files from workflow patterns (Issue #208).
 *
 * Takes a crystallization candidate (pattern + metadata) and produces a SKILL.md
 * following the AgentSkill format. Optionally generates a helper shell script
 * when the pattern is composed entirely of exec calls.
 */

import { homedir } from "node:os";
import type { WorkflowPattern } from "../backends/workflow-store.js";
import type { CrystallizationConfig } from "../config/types/features.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

interface CrystallizationInput {
  patternId: string;
  pattern: WorkflowPattern;
}

interface CrystallizationResult {
  skillName: string;
  skillContent: string;
  /** Resolved output path for the SKILL.md (not yet written to disk — requires approval) */
  proposedOutputPath: string;
  /** Whether a companion shell script was generated */
  hasScript: boolean;
  /** Shell script content if hasScript === true */
  scriptContent?: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Derive a kebab-case skill name from example goals and tool sequence.
 * Prefers the first example goal, falls back to tool sequence hash.
 */
export function deriveSkillName(exampleGoals: string[], toolSequence: string[], patternId: string): string {
  // Try to extract a short phrase from the first example goal
  const firstGoal = exampleGoals[0];
  if (firstGoal && firstGoal.trim().length > 0) {
    const slug = firstGoal
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, "")
      .trim()
      .split(/\s+/)
      .slice(0, 4)
      .join("-");
    if (slug.length >= 3) return `auto-${slug}`;
  }

  // Fall back: use the first two tool names + hash fragment (lowercase for consistency)
  const toolSlug = toolSequence
    .slice(0, 2)
    .join("-")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-");
  return `auto-${toolSlug}-${patternId.slice(0, 6)}`;
}

/**
 * Check whether a tool sequence is entirely exec calls (shell-automatable).
 */
export function isExecOnlySequence(toolSequence: string[]): boolean {
  return toolSequence.length > 0 && toolSequence.every((t) => t === "exec");
}

// ---------------------------------------------------------------------------
// SKILL.md template builder
// ---------------------------------------------------------------------------

function buildSkillContent(skillName: string, pattern: WorkflowPattern, patternId: string, createdAt: string): string {
  const toolSequence = pattern.toolSequence;
  const successPct = Math.round(pattern.successRate * 100);
  const exampleGoalsText =
    pattern.exampleGoals.length > 0
      ? pattern.exampleGoals.map((g) => `- ${g.replace(/\n/g, " ")}`).join("\n")
      : "- (no example goals recorded)";

  const stepsText = toolSequence
    .map((tool, i) => `${i + 1}. Use \`${tool}\` only for the bounded task, then verify before continuing.`)
    .join("\n");

  const antiPatterns =
    pattern.failureCount > 0
      ? `- Do not assume the pattern always succeeds (${pattern.failureCount} recorded failures). Add a verification gate and record feedback on failure.\n- Do not paste raw logs or tool-call blobs into this skill; summarize as workflow phases and checklists.\n- Do not broaden scope beyond the example goals; ask for clarification on near-miss tasks.\n- Do not claim implementation work is complete unless a PR exists or the change is merged to \`main\`.\n- Do not poll subagents in a tight loop; yield and wait for push-based completion.`
      : `- Do not paste raw logs or tool-call blobs into this skill; summarize as workflow phases and checklists.\n- Do not broaden scope beyond the example goals; ask for clarification on near-miss tasks.\n- Do not treat tool sequencing as sufficient; always include verification and failure handling.\n- Do not claim implementation work is complete unless a PR exists or the change is merged to \`main\`.\n- Do not poll subagents in a tight loop; yield and wait for push-based completion.`;

  return `---
name: ${skillName}
description: Reusable workflow distilled from a repeated tool-sequence pattern (${successPct}% success). Use for tasks that match the activation examples.
category: crystallized
provenance: workflow-pattern:${patternId}
generated_at: ${createdAt}
---

# ${skillName}

> Auto-crystallized from workflow pattern on ${createdAt}.
> **Do not edit this file manually** — it will be regenerated or overwritten.

## Description

This skill was automatically generated from a repeated tool sequence pattern.
Use it as a reference for tasks that match the example goals below.

**Source pattern ID:** \`${patternId}\`  
**Success rate:** ${successPct}% (${pattern.successCount}/${pattern.totalCount} executions)  
**Average duration:** ${pattern.avgDurationMs}ms

## When to Activate

${exampleGoalsText}

## Do Not Use When
- The task requires destructive changes, external sends/posts, credential access, or network writes without explicit human approval.
- The user request is broader than the example goals or requires unrelated troubleshooting.
- The workflow requires copying full logs/transcripts into the skill instead of summarizing.

## Workflow

${stepsText}

## Verification
- Confirm the output matches the user’s request (objective checks preferred).
- Keep snippets compact; avoid pasting long command output or transcripts.
- If a step fails, stop and record a failure signal rather than improvising.

## Anti-patterns / Known Failures
${antiPatterns}

## Examples
- Good: Pick one activation example, follow the ordered workflow, and stop once verification passes.
- Bad: Paste a long transcript/log dump into the skill instead of extracting a reusable checklist.

## Related tools/skills
- Related tool: \`memory_procedure_feedback\` (record failures/success so anti-patterns improve over time).
- Related system: the workflow pattern detector + crystallization store (proposals require review).

## Provenance
- Source pattern ID: \`${patternId}\`
- Generated at: ${createdAt}
- Tool sequence signature (compact):

Tool sequence signature:
\`\`\`
${toolSequence.join(" → ")}
\`\`\`
`;
}

// ---------------------------------------------------------------------------
// SkillCrystallizer
// ---------------------------------------------------------------------------

export class SkillCrystallizer {
  constructor(private readonly cfg: CrystallizationConfig) {}

  /**
   * Generate a SKILL.md from a crystallization candidate.
   * Does NOT write to disk — returns content + proposed path for the approval flow.
   */
  crystallize(input: CrystallizationInput): CrystallizationResult {
    const { patternId, pattern } = input;
    const createdAt = new Date().toISOString().slice(0, 10);

    const skillName = deriveSkillName(pattern.exampleGoals, pattern.toolSequence, patternId);
    const skillContent = buildSkillContent(skillName, pattern, patternId, createdAt);

    // Resolve output directory (expand ~ for home dir)
    const outputDir = this.cfg.outputDir.replace(/^~/, getEnv("HOME") || homedir());
    const proposedOutputPath = `${outputDir}/${skillName}/SKILL.md`;

    // Generate shell script for exec-only sequences
    const hasScript = isExecOnlySequence(pattern.toolSequence);
    const scriptContent = hasScript ? buildShellScript(skillName, pattern, patternId) : undefined;

    return {
      skillName,
      skillContent,
      proposedOutputPath,
      hasScript,
      scriptContent,
    };
  }
}

// ---------------------------------------------------------------------------
// Shell script builder (exec-only patterns)
// ---------------------------------------------------------------------------

function buildShellScript(skillName: string, pattern: WorkflowPattern, patternId: string): string {
  const steps = pattern.toolSequence.map((_, i) => `# Step ${i + 1}: exec call`).join("\n");
  return `#!/usr/bin/env bash
# Auto-generated shell script for skill: ${skillName}
# Pattern ID: ${patternId}
# Steps: ${pattern.toolSequence.length} exec call(s)
# Success rate: ${Math.round(pattern.successRate * 100)}%

set -euo pipefail

${steps}

echo "Skill '${skillName}' scaffold generated. Replace each '# Step N' block with concrete commands before use."
`;
}
