/**
 * Core ↔ policy-provider dispatch authorization ABI (v1).
 *
 * This is intentionally dependency-free so OpenClaw core can consume the same
 * contract without importing this plugin. Core owns the irreversible boundary:
 * it builds this context, atomically reserves budget, persists the returned
 * opaque grant on the child run/session, and verifies it before launch.
 */
export const CORE_DISPATCH_AUTHORIZATION_ABI_VERSION = 1 as const;

export type CoreDispatchOrigin = "sessions_spawn_native" | "sessions_spawn_acp" | "cron_agent_turn" | "gateway_direct";
export type DispatchBudgetCaps = Readonly<{
  maxTotalTokens?: number;
  maxDispatchTokens?: number;
  maxWallTimeMs?: number;
  maxDispatches?: number;
}>;
export type CoreDispatchContext = Readonly<{
  abiVersion: typeof CORE_DISPATCH_AUTHORIZATION_ABI_VERSION;
  traceId: string;
  origin: CoreDispatchOrigin;
  requester: Readonly<{ sessionId: string; sessionKey?: string; agentId?: string }>;
  parentRunId?: string;
  parentSessionId?: string;
  target: Readonly<{ agentId: string; runtime: "subagent" | "acp" }>;
  goalId?: string;
  requestedBudget: DispatchBudgetCaps;
  /** Host-derived tool inputs. Providers must not trust model-provided aliases. */
  attributes: Readonly<Record<string, unknown>>;
}>;
export type DispatchAuthorizationGrant = Readonly<{
  /** Opaque, short-lived value generated by the provider/core; never model input. */
  id: string;
  expiresAt: string;
  budget: DispatchBudgetCaps;
  policyRef?: string;
}>;
export type DispatchAuthorizationDecision =
  | Readonly<{ kind: "abstain"; reason: string }>
  | Readonly<{ kind: "deny"; reason: string }>
  | Readonly<{ kind: "allow"; grant: DispatchAuthorizationGrant }>;

/**
 * Core calls this before allocating a child run/session on every dispatch
 * surface. `allow` is not sufficient to launch: core must atomically reserve
 * grant.budget, persist the grant, and reject missing/expired grants at launch.
 */
export interface CoreDispatchAuthorizationProvider {
  readonly abiVersion: typeof CORE_DISPATCH_AUTHORIZATION_ABI_VERSION;
  authorize(context: CoreDispatchContext): Promise<DispatchAuthorizationDecision>;
}
